# Generated by Django 5.2.12 on 2026-04-02 09:06

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("financial_year", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("place_of_supply", models.CharField(max_length=100)),
                ("place_of_supply_code", models.CharField(max_length=5)),
                ("reverse_charge", models.BooleanField(default=False)),
                ("is_interstate", models.BooleanField(default=False)),
                ("transport_mode", models.CharField(blank=True, max_length=100)),
                ("vehicle_number", models.CharField(blank=True, max_length=50)),
                ("station", models.CharField(blank=True, max_length=100)),
                ("eway_bill_number", models.CharField(blank=True, max_length=50)),
                ("po_number", models.CharField(blank=True, max_length=100)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_address", models.TextField(blank=True)),
                ("customer_gstin", models.CharField(blank=True, max_length=15)),
                ("customer_state", models.CharField(blank=True, max_length=100)),
                ("customer_state_code", models.CharField(blank=True, max_length=5)),
                ("customer_mobile", models.CharField(blank=True, max_length=15)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("shipping_name", models.CharField(blank=True, max_length=255)),
                ("shipping_address", models.TextField(blank=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_state_code", models.CharField(blank=True, max_length=5)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_cgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_sgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_igst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_cess",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("amount_in_words", models.CharField(blank=True, max_length=500)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_ifsc", models.CharField(blank=True, max_length=15)),
                ("bank_branch", models.CharField(blank=True, max_length=255)),
                ("bank_upi_id", models.CharField(blank=True, max_length=100)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("irn", models.CharField(blank=True, max_length=100)),
                ("irn_generated_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="company.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date", "-created_at"],
                "unique_together": {("company", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sr_no", models.PositiveIntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("hsn_code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("gst_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sr_no"],
            },
        ),
    ]
