# Generated by Django 5.2.12 on 2026-04-02 07:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("unit_division", models.CharField(blank=True, max_length=255)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "state_code",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="State code must be exactly 2 digits",
                                regex="^[0-9]{2}$",
                            )
                        ],
                    ),
                ),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid PAN",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid GSTIN",
                                regex="^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                ("udyam_number", models.CharField(blank=True, max_length=25)),
                ("mobile_primary", models.CharField(max_length=15)),
                ("mobile_secondary", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/logos/"
                    ),
                ),
                ("logo_text", models.CharField(blank=True, max_length=6)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/signatures/"
                    ),
                ),
                ("authorised_signatory", models.CharField(blank=True, max_length=255)),
                ("is_msme", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
            },
        ),
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("branch_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=15)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("savings", "Savings"), ("current", "Current")],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("swift_code", models.CharField(blank=True, max_length=15)),
                ("ad_code", models.CharField(blank=True, max_length=20)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/qr_codes/"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="company.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Detail",
                "ordering": ["-is_primary", "bank_name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV", max_length=20)),
                ("financial_year", models.CharField(default="25-26", max_length=10)),
                ("invoice_counter", models.PositiveIntegerField(default=1)),
                ("counter_reset_yearly", models.BooleanField(default=True)),
                ("default_due_days", models.PositiveIntegerField(default=30)),
                (
                    "default_transport",
                    models.CharField(default="BY Hand", max_length=100),
                ),
                (
                    "default_place_of_supply",
                    models.CharField(blank=True, max_length=100),
                ),
                ("reverse_charge_applicable", models.BooleanField(default=False)),
                ("einvoicing_enabled", models.BooleanField(default=False)),
                ("ewaybill_enabled", models.BooleanField(default=False)),
                ("invoice_terms", models.TextField(blank=True)),
                ("invoice_notes", models.TextField(blank=True)),
                ("show_bank_details", models.BooleanField(default=True)),
                ("show_signature", models.BooleanField(default=True)),
                ("number_of_copies", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_settings",
                        to="company.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Settings",
            },
        ),
    ]
